#!/bin/bash

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "${f}" ] && source "${f}"
    done
    unset f
fi

xsetroot -cursor_name left_ptr
numlockx on &

# exec xmonad
exec "${HOME}/.local/share/xmonad/xmonad-x86_64-linux"
